### ISSUE TITLE
同MSI403。

### ISSUE THREAD

**Issue by cs950809** [weiyichen2011/MSI-GE60-2PL-403XCN-EFI#1]
想问下作者最近使用情况咋样。我最近也在倒腾我的老403，装的小兵的最新的10.15镜像，现在刚开始弄驱动， 在弄显卡和声卡中。我看了下你的kext文件夹里，感觉好多小兵镜像自带的没删除，我是都删了后，一个一个添加精简，但是我在显卡和声卡这里遇到问题，比如声卡 我使用的ALC驱动，但是注入的我都尝试了下还是不行。

**Comment by CXZS-Git** [comment]
Sorry呀，因为体验不够好，所以我还是换回Windows了。
声卡的话我在Readme.md里面写了要安装额外的软件才可以驱动。希望能帮到你。

**Comment by cs950809** [comment]
> Sorry呀，因为体验不够好，所以我还是换回Windows了。
> 
> 声卡的话我在Readme.md里面写了要安装额外的软件才可以驱动。希望能帮到你。

thanks，我的已经自己弄好了。自己弄的体验感觉还可以。基本都可以运行。感兴趣可以看看我的github
